### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sherkon18** [travisghansen/rancher-to-argocd-controller#1] opened 2022-10-04 13:51 UTC
Is there any way you could provide a walk through on how to deploy? Even if you had a screen recording of the process from build to deploy would help.

**Comment by travisghansen** [comment] 2022-10-04 14:03
Sure. I’m traveling currently but something to be aware of is this assumes that rancher and argo are running in the same cluster.

Otherwise it’s really as simple as editing the env vars in deploy.yaml to your liking.

To see how the env vars are used you can look at this: https://github.com/travisghansen/rancher-to-argocd-controller/blob/master/hooks/rancher-to-argocd.sh

**Comment by sherkon18** [comment] 2022-10-04 18:33
Thanks @travisghansen  - Assuming I deploy correctly, please let me know if I messed up.
Steps I took:
- cloned project
- created env variables as documented
- made changes to deploy.yaml with my uri and env id, and I made changes to the name spaces for each service (this could be a env variable*)
- command issued: kubectl apply -f deploy.yaml -n argo-cd #my name space is different

Looking at the logs for argo-to-rancher pod, I see the following.
error: the server doesn't have a resource type \"users\"
error: the server doesn't have a resource type \"tokens\"

Did I miss something? Seems like I am missing around permissions.

**Comment by travisghansen** [comment] 2022-10-04 18:37
Those resources are provided by rancher itself. Is it running in the same cluster as this project and argocd?

**Comment by sherkon18** [comment] 2022-10-05 02:13
> Those resources are provided by rancher itself. Is it running in the same cluster as this project and argocd?

They are.

**Comment by sherkon18** [comment] 2022-10-05 02:20
This is the entire error message.

`{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"error","msg":"Hook failed. Will retry after delay. Failed count is 6. Error: rancher-to-argocd.sh FAILED: exit status 1","queue":"main","task":"HookRun","time":"2022-10-05T02:19:27Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"Execute hook","queue":"main","task":"HookRun","time":"2022-10-05T02:19:48Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"error: the server doesn't have a resource type \"users\"","output":"stderr","queue":"main","task":"HookRun","time":"2022-10-05T02:19:49Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"error: the server doesn't have a resource type \"tokens\"","output":"stderr","queue":"main","task":"HookRun","time":"2022-10-05T02:19:49Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"handling cluster: local","output":"stdout","queue":"main","task":"HookRun","time":"2022-10-05T02:19:49Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"cluster local display name: local","output":"stdout","queue":"main","task":"HookRun","time":"2022-10-05T02:19:49Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"error: error parsing STDIN: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context","output":"stderr","queue":"main","task":"HookRun","time":"2022-10-05T02:19:49Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"error","msg":"Hook failed. Will retry after delay. Failed count is 7. Error: rancher-to-argocd.sh FAILED: exit status 1","queue":"main","task":"HookRun","time":"2022-10-05T02:19:49Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"Execute hook","queue":"main","task":"HookRun","time":"2022-10-05T02:20:21Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"error: the server doesn't have a resource type \"users\"","output":"stderr","queue":"main","task":"HookRun","time":"2022-10-05T02:20:21Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"error: the server doesn't have a resource type \"tokens\"","output":"stderr","queue":"main","task":"HookRun","time":"2022-10-05T02:20:22Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"handling cluster: local","output":"stdout","queue":"main","task":"HookRun","time":"2022-10-05T02:20:22Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"cluster local display name: local","output":"stdout","queue":"main","task":"HookRun","time":"2022-10-05T02:20:22Z"}
{"binding":"kubernetes","event":"kubernetes","hook":"rancher-to-argocd.sh","level":"info","msg":"error: error parsing STDIN: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context","output":"stderr","queue":"main","task":"HookRun","time":"2022-10-05T02:20:23Z"}`

**Comment by travisghansen** [comment] 2022-10-05 02:35
What version of rancher are you running?

**Comment by sherkon18** [comment] 2022-10-05 02:39
![Screen Shot 2022-10-04 at 10 36 34 PM](https://user-images.githubusercontent.com/5869974/193969175-ceefd6e8-ad73-4ef3-b249-89d64d06b095.png)
These are the env I set.

**Comment by sherkon18** [comment] 2022-10-05 02:40
> What version of rancher are you running?

2.5.5

**Comment by travisghansen** [comment] 2022-10-05 03:12
`kubectl get crds`

**Comment by sherkon18** [comment] 2022-10-05 03:31
> `kubectl get crds`

`alertmanagers.monitoring.coreos.com           2020-12-08T20:23:48Z
aplogconfs.appprotect.f5.com                  2022-01-24T13:26:43Z
applications.argoproj.io                      2021-06-25T17:23:12Z
applicationsets.argoproj.io                   2022-07-29T17:56:18Z
appolicies.appprotect.f5.com                  2022-01-24T13:26:43Z
appprojects.argoproj.io                       2021-06-25T17:23:14Z
apps.catalog.cattle.io                        2021-02-04T20:34:05Z
apusersigs.appprotect.f5.com                  2022-01-24T13:26:43Z
argocdextensions.argoproj.io                  2022-09-29T14:46:17Z
bgpconfigurations.crd.projectcalico.org       2020-12-08T20:18:37Z
bgppeers.crd.projectcalico.org                2020-12-08T20:18:37Z
blockaffinities.crd.projectcalico.org         2020-12-08T20:18:37Z
clusterauthtokens.cluster.cattle.io           2020-12-08T20:19:01Z
clusterflows.logging.banzaicloud.io           2022-03-18T15:04:53Z
clusterinformations.crd.projectcalico.org     2020-12-08T20:18:37Z
clusteroutputs.logging.banzaicloud.io         2022-03-18T15:04:53Z
clusterrepos.catalog.cattle.io                2021-02-04T20:34:05Z
clusters.management.cattle.io                 2021-02-04T20:34:05Z
clusteruserattributes.cluster.cattle.io       2020-12-08T20:19:01Z
features.management.cattle.io                 2021-02-04T20:34:05Z
felixconfigurations.crd.projectcalico.org     2020-12-08T20:18:37Z
flows.logging.banzaicloud.io                  2022-03-18T15:04:53Z
globalconfigurations.k8s.nginx.org            2022-01-24T13:26:43Z
globalnetworkpolicies.crd.projectcalico.org   2020-12-08T20:18:37Z
globalnetworksets.crd.projectcalico.org       2020-12-08T20:18:37Z
hostendpoints.crd.projectcalico.org           2020-12-08T20:18:37Z
ipamblocks.crd.projectcalico.org              2020-12-08T20:18:37Z
ipamconfigs.crd.projectcalico.org             2020-12-08T20:18:37Z
ipamhandles.crd.projectcalico.org             2020-12-08T20:18:37Z
ippools.crd.projectcalico.org                 2020-12-08T20:18:37Z
loggings.logging.banzaicloud.io               2022-03-18T15:04:53Z
networkpolicies.crd.projectcalico.org         2020-12-08T20:18:37Z
networksets.crd.projectcalico.org             2020-12-08T20:18:37Z
operations.catalog.cattle.io                  2021-02-04T20:34:05Z
outputs.logging.banzaicloud.io                2022-03-18T15:04:53Z
podmonitors.monitoring.coreos.com             2020-12-08T20:53:38Z
policies.k8s.nginx.org                        2022-01-24T13:26:43Z
preferences.management.cattle.io              2021-02-04T20:34:05Z
prometheuses.monitoring.coreos.com            2020-12-08T20:23:48Z
prometheusrules.monitoring.coreos.com         2020-12-08T20:23:48Z
servicemonitors.monitoring.coreos.com         2020-12-08T20:23:48Z
settings.management.cattle.io                 2021-02-04T20:34:05Z
thanosrulers.monitoring.coreos.com            2020-12-08T20:53:39Z
transportservers.k8s.nginx.org                2022-01-24T13:26:43Z
virtualserverroutes.k8s.nginx.org             2022-01-24T13:26:44Z
virtualservers.k8s.nginx.org                  2022-01-24T13:26:44Z`

**Comment by travisghansen** [comment] 2022-10-05 04:07
How exactly did you install rancher in this cluster? Maybe something changed between 2.5 and 2.6 with how all the data is stored :( I may have had 2.6 installed when doing development and so never saw the behavior on 2.5.

```
kubectl get crds | egrep 'rancher|rke|cattle'
egrep: warning: egrep is obsolescent; using grep -E
amazonec2configs.rke-machine-config.cattle.io                   2021-10-11T22:18:28Z
amazonec2machines.rke-machine.cattle.io                         2021-10-11T22:18:29Z
amazonec2machinetemplates.rke-machine.cattle.io                 2021-10-11T22:18:29Z
apiservices.management.cattle.io                                2021-10-11T22:13:47Z
apprevisions.project.cattle.io                                  2020-02-25T22:03:08Z
apps.catalog.cattle.io                                          2020-12-09T20:25:30Z
apps.project.cattle.io                                          2020-02-25T22:03:08Z
authconfigs.management.cattle.io                                2020-02-25T22:03:08Z
azureconfigs.rke-machine-config.cattle.io                       2021-10-11T22:18:28Z
azuremachines.rke-machine.cattle.io                             2021-10-11T22:18:28Z
azuremachinetemplates.rke-machine.cattle.io                     2021-10-11T22:18:28Z
bundledeployments.fleet.cattle.io                               2020-12-09T20:26:25Z
bundlenamespacemappings.fleet.cattle.io                         2020-12-09T20:26:25Z
bundles.fleet.cattle.io                                         2020-12-09T20:26:25Z
catalogs.management.cattle.io                                   2020-02-25T22:03:08Z
catalogtemplates.management.cattle.io                           2020-02-25T22:03:08Z
catalogtemplateversions.management.cattle.io                    2020-02-25T22:03:08Z
cisbenchmarkversions.management.cattle.io                       2020-05-20T21:59:27Z
cisconfigs.management.cattle.io                                 2020-05-20T21:59:27Z
clusteralertgroups.management.cattle.io                         2020-02-25T22:02:42Z
clusteralertrules.management.cattle.io                          2020-02-25T22:02:44Z
clusteralerts.management.cattle.io                              2020-02-25T22:02:42Z
clustercatalogs.management.cattle.io                            2020-02-25T22:02:43Z
clustergroups.fleet.cattle.io                                   2020-12-09T20:26:25Z
clusterloggings.management.cattle.io                            2020-02-25T22:02:43Z
clustermonitorgraphs.management.cattle.io                       2020-02-25T22:02:44Z
clusterregistrations.fleet.cattle.io                            2020-12-09T20:26:25Z
clusterregistrationtokens.fleet.cattle.io                       2020-12-09T20:26:25Z
clusterregistrationtokens.management.cattle.io                  2020-02-25T22:02:44Z
clusterrepos.catalog.cattle.io                                  2020-12-09T20:25:30Z
clusterroletemplatebindings.management.cattle.io                2020-02-25T22:02:44Z
clusters.fleet.cattle.io                                        2020-12-09T20:26:25Z
clusters.management.cattle.io                                   2020-02-25T22:02:45Z
clusters.provisioning.cattle.io                                 2021-10-11T22:13:54Z
clusters.rancher.cattle.io                                      2020-12-09T20:27:05Z
clusterscans.management.cattle.io                               2020-02-25T22:02:45Z
clustertemplaterevisions.management.cattle.io                   2020-02-25T22:03:17Z
clustertemplates.management.cattle.io                           2020-02-25T22:03:17Z
composeconfigs.management.cattle.io                             2020-02-25T22:02:45Z
contents.fleet.cattle.io                                        2020-12-09T20:26:25Z
custommachines.rke.cattle.io                                    2021-10-11T22:13:58Z
digitaloceanconfigs.rke-machine-config.cattle.io                2021-10-11T22:18:28Z
digitaloceanmachines.rke-machine.cattle.io                      2021-10-11T22:18:28Z
digitaloceanmachinetemplates.rke-machine.cattle.io              2021-10-11T22:18:28Z
dynamicschemas.management.cattle.io                             2020-02-25T22:02:45Z
etcdbackups.management.cattle.io                                2020-02-25T22:02:45Z
etcdsnapshots.rke.cattle.io                                     2022-07-14T02:26:13Z
features.management.cattle.io                                   2020-02-25T22:02:45Z
fleetworkspaces.management.cattle.io                            2020-12-09T20:25:39Z
gitjobs.gitjob.cattle.io                                        2020-12-09T20:26:25Z
gitreporestrictions.fleet.cattle.io                             2020-12-09T20:26:25Z
gitrepos.fleet.cattle.io                                        2020-12-09T20:26:25Z
globaldnses.management.cattle.io                                2020-02-25T22:03:16Z
globaldnsproviders.management.cattle.io                         2020-02-25T22:03:17Z
globalrolebindings.management.cattle.io                         2020-02-25T22:02:45Z
globalroles.management.cattle.io                                2020-02-25T22:02:46Z
groupmembers.management.cattle.io                               2020-02-25T22:02:46Z
groups.management.cattle.io                                     2020-02-25T22:02:46Z
harvesterconfigs.rke-machine-config.cattle.io                   2022-01-29T04:41:10Z
harvestermachines.rke-machine.cattle.io                         2022-01-29T04:41:10Z
harvestermachinetemplates.rke-machine.cattle.io                 2022-01-29T04:41:10Z
imagescans.fleet.cattle.io                                      2021-10-11T22:23:39Z
kontainerdrivers.management.cattle.io                           2020-02-25T22:02:46Z
linodeconfigs.rke-machine-config.cattle.io                      2021-10-11T22:18:28Z
linodemachines.rke-machine.cattle.io                            2021-10-11T22:18:28Z
linodemachinetemplates.rke-machine.cattle.io                    2021-10-11T22:18:28Z
listenconfigs.management.cattle.io                              2020-02-25T22:02:46Z
managedcharts.management.cattle.io                              2021-10-11T22:13:53Z
monitormetrics.management.cattle.io                             2020-02-25T22:02:46Z
multiclusterapprevisions.management.cattle.io                   2020-02-25T22:02:46Z
multiclusterapps.management.cattle.io                           2020-02-25T22:02:46Z
navlinks.ui.cattle.io                                           2021-10-11T22:13:47Z
nodedrivers.management.cattle.io                                2020-02-25T22:02:46Z
nodepools.management.cattle.io                                  2020-02-25T22:02:46Z
nodes.management.cattle.io                                      2020-02-25T22:02:46Z
nodetemplates.management.cattle.io                              2020-02-25T22:02:46Z
notifiers.management.cattle.io                                  2020-02-25T22:02:46Z
operations.catalog.cattle.io                                    2020-12-09T20:25:30Z
pipelineexecutions.project.cattle.io                            2020-02-25T22:03:08Z
pipelines.project.cattle.io                                     2020-02-25T22:02:42Z
pipelinesettings.project.cattle.io                              2020-02-25T22:03:08Z
podsecuritypolicytemplateprojectbindings.management.cattle.io   2020-02-25T22:02:46Z
podsecuritypolicytemplates.management.cattle.io                 2020-02-25T22:02:46Z
preferences.management.cattle.io                                2020-02-25T22:03:12Z
projectalertgroups.management.cattle.io                         2020-02-25T22:03:13Z
projectalertrules.management.cattle.io                          2020-02-25T22:03:13Z
projectalerts.management.cattle.io                              2020-02-25T22:03:12Z
projectcatalogs.management.cattle.io                            2020-02-25T22:03:13Z
projectloggings.management.cattle.io                            2020-02-25T22:03:13Z
projectmonitorgraphs.management.cattle.io                       2020-02-25T22:03:13Z
projectnetworkpolicies.management.cattle.io                     2020-02-25T22:03:14Z
projectroletemplatebindings.management.cattle.io                2020-02-25T22:03:14Z
projects.management.cattle.io                                   2020-02-25T22:03:14Z
projects.rancher.cattle.io                                      2020-12-09T20:27:05Z
rkeaddons.management.cattle.io                                  2020-02-25T22:03:15Z
rkebootstraps.rke.cattle.io                                     2021-10-11T22:13:56Z
rkebootstraptemplates.rke.cattle.io                             2021-10-11T22:13:57Z
rkeclusters.rke.cattle.io                                       2021-10-11T22:13:55Z
rkecontrolplanes.rke.cattle.io                                  2021-10-11T22:13:56Z
rkek8sserviceoptions.management.cattle.io                       2020-02-25T22:03:14Z
rkek8ssystemimages.management.cattle.io                         2020-02-25T22:03:14Z
roletemplatebindings.rancher.cattle.io                          2020-12-09T20:27:05Z
roletemplates.management.cattle.io                              2020-02-25T22:03:15Z
roletemplates.rancher.cattle.io                                 2020-12-09T20:27:05Z
samltokens.management.cattle.io                                 2020-12-09T20:25:41Z
settings.management.cattle.io                                   2020-02-25T22:03:15Z
sourcecodecredentials.project.cattle.io                         2020-02-25T22:02:42Z
sourcecodeproviderconfigs.project.cattle.io                     2020-02-25T22:02:42Z
sourcecoderepositories.project.cattle.io                        2020-02-25T22:02:43Z
templatecontents.management.cattle.io                           2020-02-25T22:03:16Z
templates.management.cattle.io                                  2020-02-25T22:03:15Z
templateversions.management.cattle.io                           2020-02-25T22:03:15Z
tokens.management.cattle.io                                     2020-02-25T22:03:16Z
userattributes.management.cattle.io                             2020-02-25T22:03:16Z
users.management.cattle.io                                      2020-02-25T22:03:16Z
vmwarevsphereconfigs.rke-machine-config.cattle.io               2021-10-11T22:18:28Z
vmwarevspheremachines.rke-machine.cattle.io                     2021-10-11T22:18:28Z
vmwarevspheremachinetemplates.rke-machine.cattle.io             2021-10-11T22:18:28Z
```

**Comment by sherkon18** [comment] 2022-10-05 11:56
> How exactly did you install rancher in this cluster? Maybe something changed between 2.5 and 2.6 with how all the data is stored :( I may have had 2.6 installed when doing development and so never saw the behavior on 2.5.
> 
> ```
> kubectl get crds | egrep 'rancher|rke|cattle'
> egrep: warning: egrep is obsolescent; using grep -E
> amazonec2configs.rke-machine-config.cattle.io                   2021-10-11T22:18:28Z
> amazonec2machines.rke-machine.cattle.io                         2021-10-11T22:18:29Z
> amazonec2machinetemplates.rke-machine.cattle.io                 2021-10-11T22:18:29Z
> apiservices.management.cattle.io                                2021-10-11T22:13:47Z
> apprevisions.project.cattle.io                                  2020-02-25T22:03:08Z
> apps.catalog.cattle.io                                          2020-12-09T20:25:30Z
> apps.project.cattle.io                                          2020-02-25T22:03:08Z
> authconfigs.management.cattle.io                                2020-02-25T22:03:08Z
> azureconfigs.rke-machine-config.cattle.io                       2021-10-11T22:18:28Z
> azuremachines.rke-machine.cattle.io                             2021-10-11T22:18:28Z
> azuremachinetemplates.rke-machine.cattle.io                     2021-10-11T22:18:28Z
> bundledeployments.fleet.cattle.io                               2020-12-09T20:26:25Z
> bundlenamespacemappings.fleet.cattle.io                         2020-12-09T20:26:25Z
> bundles.fleet.cattle.io                                         2020-12-09T20:26:25Z
> catalogs.management.cattle.io                                   2020-02-25T22:03:08Z
> catalogtemplates.management.cattle.io                           2020-02-25T22:03:08Z
> catalogtemplateversions.management.cattle.io                    2020-02-25T22:03:08Z
> cisbenchmarkversions.management.cattle.io                       2020-05-20T21:59:27Z
> cisconfigs.management.cattle.io                                 2020-05-20T21:59:27Z
> clusteralertgroups.management.cattle.io                         2020-02-25T22:02:42Z
> clusteralertrules.management.cattle.io                          2020-02-25T22:02:44Z
> clusteralerts.management.cattle.io                              2020-02-25T22:02:42Z
> clustercatalogs.management.cattle.io                            2020-02-25T22:02:43Z
> clustergroups.fleet.cattle.io                                   2020-12-09T20:26:25Z
> clusterloggings.management.cattle.io                            2020-02-25T22:02:43Z
> clustermonitorgraphs.management.cattle.io                       2020-02-25T22:02:44Z
> clusterregistrations.fleet.cattle.io                            2020-12-09T20:26:25Z
> clusterregistrationtokens.fleet.cattle.io                       2020-12-09T20:26:25Z
> clusterregistrationtokens.management.cattle.io                  2020-02-25T22:02:44Z
> clusterrepos.catalog.cattle.io                                  2020-12-09T20:25:30Z
> clusterroletemplatebindings.management.cattle.io                2020-02-25T22:02:44Z
> clusters.fleet.cattle.io                                        2020-12-09T20:26:25Z
> clusters.management.cattle.io                                   2020-02-25T22:02:45Z
> clusters.provisioning.cattle.io                                 2021-10-11T22:13:54Z
> clusters.rancher.cattle.io                                      2020-12-09T20:27:05Z
> clusterscans.management.cattle.io                               2020-02-25T22:02:45Z
> clustertemplaterevisions.management.cattle.io                   2020-02-25T22:03:17Z
> clustertemplates.management.cattle.io                           2020-02-25T22:03:17Z
> composeconfigs.management.cattle.io                             2020-02-25T22:02:45Z
> contents.fleet.cattle.io                                        2020-12-09T20:26:25Z
> custommachines.rke.cattle.io                                    2021-10-11T22:13:58Z
> digitaloceanconfigs.rke-machine-config.cattle.io                2021-10-11T22:18:28Z
> digitaloceanmachines.rke-machine.cattle.io                      2021-10-11T22:18:28Z
> digitaloceanmachinetemplates.rke-machine.cattle.io              2021-10-11T22:18:28Z
> dynamicschemas.management.cattle.io                             2020-02-25T22:02:45Z
> etcdbackups.management.cattle.io                                2020-02-25T22:02:45Z
> etcdsnapshots.rke.cattle.io                                     2022-07-14T02:26:13Z
> features.management.cattle.io                                   2020-02-25T22:02:45Z
> fleetworkspaces.management.cattle.io                            2020-12-09T20:25:39Z
> gitjobs.gitjob.cattle.io                                        2020-12-09T20:26:25Z
> gitreporestrictions.fleet.cattle.io                             2020-12-09T20:26:25Z
> gitrepos.fleet.cattle.io                                        2020-12-09T20:26:25Z
> globaldnses.management.cattle.io                                2020-02-25T22:03:16Z
> globaldnsproviders.management.cattle.io                         2020-02-25T22:03:17Z
> globalrolebindings.management.cattle.io                         2020-02-25T22:02:45Z
> globalroles.management.cattle.io                                2020-02-25T22:02:46Z
> groupmembers.management.cattle.io                               2020-02-25T22:02:46Z
> groups.management.cattle.io                                     2020-02-25T22:02:46Z
> harvesterconfigs.rke-machine-config.cattle.io                   2022-01-29T04:41:10Z
> harvestermachines.rke-machine.cattle.io                         2022-01-29T04:41:10Z
> harvestermachinetemplates.rke-machine.cattle.io                 2022-01-29T04:41:10Z
> imagescans.fleet.cattle.io                                      2021-10-11T22:23:39Z
> kontainerdrivers.management.cattle.io                           2020-02-25T22:02:46Z
> linodeconfigs.rke-machine-config.cattle.io                      2021-10-11T22:18:28Z
> linodemachines.rke-machine.cattle.io                            2021-10-11T22:18:28Z
> linodemachinetemplates.rke-machine.cattle.io                    2021-10-11T22:18:28Z
> listenconfigs.management.cattle.io                              2020-02-25T22:02:46Z
> managedcharts.management.cattle.io                              2021-10-11T22:13:53Z
> monitormetrics.management.cattle.io                             2020-02-25T22:02:46Z
> multiclusterapprevisions.management.cattle.io                   2020-02-25T22:02:46Z
> multiclusterapps.management.cattle.io                           2020-02-25T22:02:46Z
> navlinks.ui.cattle.io                                           2021-10-11T22:13:47Z
> nodedrivers.management.cattle.io                                2020-02-25T22:02:46Z
> nodepools.management.cattle.io                                  2020-02-25T22:02:46Z
> nodes.management.cattle.io                                      2020-02-25T22:02:46Z
> nodetemplates.management.cattle.io                              2020-02-25T22:02:46Z
> notifiers.management.cattle.io                                  2020-02-25T22:02:46Z
> operations.catalog.cattle.io                                    2020-12-09T20:25:30Z
> pipelineexecutions.project.cattle.io                            2020-02-25T22:03:08Z
> pipelines.project.cattle.io                                     2020-02-25T22:02:42Z
> pipelinesettings.project.cattle.io                              2020-02-25T22:03:08Z
> podsecuritypolicytemplateprojectbindings.management.cattle.io   2020-02-25T22:02:46Z
> podsecuritypolicytemplates.management.cattle.io                 2020-02-25T22:02:46Z
> preferences.management.cattle.io                                2020-02-25T22:03:12Z
> projectalertgroups.management.cattle.io                         2020-02-25T22:03:13Z
> projectalertrules.management.cattle.io                          2020-02-25T22:03:13Z
> projectalerts.management.cattle.io                              2020-02-25T22:03:12Z
> projectcatalogs.management.cattle.io                            2020-02-25T22:03:13Z
> projectloggings.management.cattle.io                            2020-02-25T22:03:13Z
> projectmonitorgraphs.management.cattle.io                       2020-02-25T22:03:13Z
> projectnetworkpolicies.management.cattle.io                     2020-02-25T22:03:14Z
> projectroletemplatebindings.management.cattle.io                2020-02-25T22:03:14Z
> projects.management.cattle.io                                   2020-02-25T22:03:14Z
> projects.rancher.cattle.io                                      2020-12-09T20:27:05Z
> rkeaddons.management.cattle.io                                  2020-02-25T22:03:15Z
> rkebootstraps.rke.cattle.io                                     2021-10-11T22:13:56Z
> rkebootstraptemplates.rke.cattle.io                             2021-10-11T22:13:57Z
> rkeclusters.rke.cattle.io                                       2021-10-11T22:13:55Z
> rkecontrolplanes.rke.cattle.io                                  2021-10-11T22:13:56Z
> rkek8sserviceoptions.management.cattle.io                       2020-02-25T22:03:14Z
> rkek8ssystemimages.management.cattle.io                         2020-02-25T22:03:14Z
> roletemplatebindings.rancher.cattle.io                          2020-12-09T20:27:05Z
> roletemplates.management.cattle.io                              2020-02-25T22:03:15Z
> roletemplates.rancher.cattle.io                                 2020-12-09T20:27:05Z
> samltokens.management.cattle.io                                 2020-12-09T20:25:41Z
> settings.management.cattle.io                                   2020-02-25T22:03:15Z
> sourcecodecredentials.project.cattle.io                         2020-02-25T22:02:42Z
> sourcecodeproviderconfigs.project.cattle.io                     2020-02-25T22:02:42Z
> sourcecoderepositories.project.cattle.io                        2020-02-25T22:02:43Z
> templatecontents.management.cattle.io                           2020-02-25T22:03:16Z
> templates.management.cattle.io                                  2020-02-25T22:03:15Z
> templateversions.management.cattle.io                           2020-02-25T22:03:15Z
> tokens.management.cattle.io                                     2020-02-25T22:03:16Z
> userattributes.management.cattle.io                             2020-02-25T22:03:16Z
> users.management.cattle.io                                      2020-02-25T22:03:16Z
> vmwarevsphereconfigs.rke-machine-config.cattle.io               2021-10-11T22:18:28Z
> vmwarevspheremachines.rke-machine.cattle.io                     2021-10-11T22:18:28Z
> vmwarevspheremachinetemplates.rke-machine.cattle.io             2021-10-11T22:18:28Z
> ```

I installed Rancher via Helm.

**Comment by travisghansen** [comment] 2022-10-05 13:42
Anything preventing you from upgrading to the 2.6 train?

**Comment by sherkon18** [comment] 2022-10-05 15:52
> Anything preventing you from upgrading to the 2.6 train?

Not in my hands. I will install 2.6 on another server and test it there. I will report back.

**Comment by DaliborLabudovicGP** [comment] 2023-05-15 14:29
Travis - sorry for the late response. Deployed on 2.7.3 and it works as intended. Thanks, feel free to close the issue.

**Closed as completed** 2023-05-15 14:32 UTC
